apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: inoffice-crontab
  namespace: inoffice
spec:
  schedule: "5 16 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: inoffice-cron
              image: ghcr.io/silvercory/inoffice:latest
              imagePullPolicy: Always
              command:
                - /bin/sh
                - -c
                - inoffice_cron
          restartPolicy: OnFailure