apiVersion: batch/v1
kind: CronJob
metadata:
  name: inoffice-crontab
  namespace: inoffice
spec:
  schedule: "5 16 * * 5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: link-bot
              image: ghcr.io/SilverCory/inoffice:latest
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - inoffice_cron
          restartPolicy: OnFailure