apiVersion: apps/v1
kind: Deployment
metadata:
  name: inoffice-deployment
  namespace: inoffice
spec:
  selector:
    matchLabels:
      app: inoffice
  replicas: 1
  template:
    metadata:
      labels:
        app: inoffice
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/skip-outbound-ports: '3306'
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: link-bot
          image: ghcr.io/SilverCory/inoffice:latest
          ports:
            - containerPort: 80
          env:
            - name: GIN_MODE
              value: release
            - name: REDIS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: link-bot-config-map
                  key: redis-enabled
            - name: REDIS_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: link-bot-config-map
                  key: redis-database
            - name: REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: link-bot-redis-secret
                  key: address
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: link-bot-redis-secret
                  key: password
            - name: MYSQL_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: link-bot-config-map
                  key: mysql-enabled
            - name: MYSQL_URI
              valueFrom:
                secretKeyRef:
                  name: link-bot-mysql-secret
                  key: mysql-url
            - name: OWO_UPLOAD_URL
              valueFrom:
                secretKeyRef:
                  name: link-bot-owo-secret
                  key: owo-upload-url
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: link-bot-discord-token-secret
                  key: discord-bot-token
            - name: DISCORD_APPLICATION_ID
              valueFrom:
                configMapKeyRef:
                  name: link-bot-config-map
                  key: discord-application-id
            - name: LINK_API_URL
              value: 'http://link-api-service.danklink.svc.cluster.local:8080'