apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inoffice-slack-secret
  namespace: inoffice
spec:
  encryptedData:
    bot-token: AgB0NFNqQ2IGBoGPRd3uLTXFR0HVKjx7ttn3fAQjivpsMMPCpva+4FOOizxj2L9VWwk2EPAVDukRVOQRWqhSfhVjFvv8hM1cYEO8GjYhx+JZM2L6T1ea0MHopdmyJfJyjV4siT4AbI0zM19X64hwT+oauYyuPMv1rzc2VbE6fn8F8d9RU6gZL3FnHblFddVC6CdybKZfIfVZkMlQShrdt2Q+HQKsFFOETPp1/lYyML8oNTc5ODHFyY5+6B89lew9U0RGEKM664PvizbfGQIVRL5AjjKQrF6eovZsqK+8/jTbG2zHCeZiCpGl0OaUy2Q9FovnU9ymH7zkHSw376i09L2k6aob+eqOHRfaYjTvPdADeG5sdxeD7nsoS4uaFxAUZLF+594ajbZ9hLc52f5d6y0CMjMSX9T6ADmjbiXg8g6zr70a9ZwqHaPVYsgE4FFQmDFeX/CjU+BCx1RU4jiMV5HftdVWhChOhKAg9Rsz/DNu5wr62vgQLe6k30NnCrhBq+nEA+gEV8R/rZvdIlgcPWgqjcu+qUunNbzoN9oqW2+d3QpRBYr2VaXAg8AAxuQoexqtffH5axGx9zNfrT/AIpYB0vl21+xz9EkOiTp2NbOo9U56TrI9olsHiB/ETMdestO4E9h40KmkFXxLHbjzRbsuAtYH1q+Wex9qB3dt4HMEGsGIVmJHDS5Fm51eaLNmspUAHsTzPykfZVGMqXFIQ5/QIEDrRH9T+g8kiLXREsYmCu6cziXjCLVULXf35TbA0jLLSm8mZ4jqiMk=
    signing-secret: AgBXc+eanLDneMQ+O92i/DaCoE+b1ssW3IZPbbwG+5Aq/ShW7muojxCXBcuLh/+IYbVjS1dNDoEY0VgyO/OGO7psu3anYFI9D/SiLUGPKxmhsEKwZz+q14MXcNAVauD6YfWxTm1i2vwC46ztJlx5RTTSVap5EMbVhUHOuvRD03EksNBln1FnYY3uuTY3wxA97Hf7V9mj5USDPZG0sRUaH4B0gX9KLY3uoZhyHUjL+JFUCG25NQNCFD53bUqZ53ZsQqwqRq800ZS71zxWj7rlZABOO7bcuV5ZYPx/QYr0rf//ZXEIAhdNUn1rWKvhGy6JuDlbL3jw1gGzLqRZp5XuyUlBko4EGORBB6ySXV2ZVvEXucehtNQFpiKIxlrmvZo1FWGOWOjyOCtEiAexBB8CnuXyIuee1f4VepYs4uTdScnMmQBspxnEBMYba1oUT3+kUABaT6bNoEpDs2woj1pCXQ8EPvN+fmX3zTaxr8TSFRQqRquJl4GJGkXCfyL9KzN+6rG0L+wvU1uEsK1p/+LLyiDuFnoPuIXhoULmdYFd6gwjfrhqbvPCzaDtFyD1COwpP3cAZO6zzxVTZk8iK4TtdGTMmf4TgAnD9XmdL4U2fJZOBjWJ6HcboF1DH1pQGK1pqO4E7PtqOW8rK7UM9e8JNTXWTH1A8Bpj3lhk6MpMf9vcnAE+QhoxmfAdQ6ONIQgM1AR+r71DOa/FmiyRqdMdN3lc85ODk4prqZLoAEp4gruxRw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: inoffice-slack-secret
      namespace: inoffice

